### ISSUE TITLE
Consider de-forking repo

### ISSUE THREAD

**Issue by dideler** [devonestes/fast-elixir#1]
There are some cons to having this as a fork of the fast-ruby repo:

- The master branch will always show as having diverged from upstream master 
  <img width="515" alt="screen shot 2017-05-22 at 22 54 29" src="https://cloud.githubusercontent.com/assets/497458/26329979/ab1af940-3f41-11e7-8a23-cb38b239590f.png">

- The number of forks is inaccurate (it shows the number of fast-ruby forks)  
  <img width="120" alt="screen shot 2017-05-22 at 22 56 12" src="https://cloud.githubusercontent.com/assets/497458/26330011/df3626e6-3f41-11e7-8e8c-b7e06c7da25a.png">

- We cannot fork this repo when we already have a fast-ruby fork 
  <img width="304" alt="screen shot 2017-05-22 at 22 52 58" src="https://cloud.githubusercontent.com/assets/497458/26329941/7441093c-3f41-11e7-81e9-9f7ce04858b7.png">

**Comment by devonestes** [comment]
Oh, yeah, that last one is a _real_ problem! I think that issue alone is reason enough to do this. Now to figure out how...

Thanks for the heads up!

**Comment by devonestes** [comment]
The lovely folks at GitHub support have taken care of this. Thanks again for the issue! 👍
