### ISSUE TITLE
concat_vs_cons code does not work

### ISSUE THREAD

**Issue by benschenker** [devonestes/fast-elixir#6]
The reducer ignores the enumerable completely, and the [example usage](https://github.com/devonestes/fast-elixir/blob/master/code/general/concat_vs_cons.exs#L57) seems incorrect.

```elixir
#expected = [0, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]
#IO.inspect(ListAdd.Fast.add_lists(0..4, [1, 2, 3]) == expected)
#IO.inspect(ListAdd.Slow.add_lists(0..4, [1, 2, 3]) == expected)
#IO.inspect(ListAdd.Medium.add_lists(0..4, [1, 2, 3]) == expected)
```
`expected` should be `[0, 1, 2, 3, 4, 1, 2, 3]` when concatenating `0..4` with `[1, 2, 3]`

https://github.com/devonestes/fast-elixir/blob/master/code/general/concat_vs_cons.exs

For ease of demonstration I used the simplest version and converted to an anonymous fn:

```elixir
iex(1)> add = fn enumerator, list ->
...(1)>     Enum.reduce(enumerator, [0], fn _, acc ->
...(1)>       acc ++ list
...(1)>     end)
...(1)>   end
#Function<12.127694169/2 in :erl_eval.expr/5>
iex(2)> add.([1], [2])
[0, 2]
```

**Comment by devonestes** [comment]
Hey! Thanks for the report.

What's actually happening there is that we're not concatenating `0..4` with `[1,2,3]`. We're using the range `0..4` just to basically say "do this thing 5 times", so in the actual call to `reduce/3` we're purposefully ignoring the enumerator.

**Comment by benschenker** [comment]
Thanks for the response. Got it, that is definitely not clear as the intent, but I guess it makes sense in this context

**Comment by bschaeffer** [comment]
```

**Comment by bschaeffer** [comment]
Thanks, @devonestes!
