### ISSUE TITLE
comment about spawn vs spawn_link:

### ISSUE THREAD

**Issue by isaac-rstor** [devonestes/fast-elixir#7]
might want to point out that in testing (unit, integration, proporty) since the program run is generally going to be ephermal, spawn() might be the way to go.

**Comment by devonestes** [comment]
A few microseconds in testing isn't going to be your bottleneck 99.999% of the time. While that's technically correct, I wouldn't want folks to even start thinking about performance optimizations in their test code, so I'm not keen on adding that.

Thanks for the note, though!
